apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customerorderservicesapp
  name: customerorderservicesapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerorderservicesapp
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: customerorderservicesapp
    spec:
      containers:
        - image: <DOCKER_IMAGE>
          imagePullPolicy: Always
          name: customerorderservicesapp
          ports:
            - containerPort: 9080
